apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    # --- REPLACE THIS LINE ---
    repoURL: 'https://github.com/Consultantsrihari/gitops-manifests.git'
    targetRevision: HEAD
    path: argo-cd/apps # Points to the directory containing all our application definitions
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true